<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>dfl</string>
	</array>
	<key>name</key>
	<string>Dataflow Language</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>match</key>
			<string>\d+</string>
			<key>name</key>
			<string>constant.numeric.dfl</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(true|false)</string>
			<key>name</key>
			<string>constant.language.dfl</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\".*\"</string>
			<key>name</key>
			<string>string.quoted.double</string>
		</dict>
		<dict>
			<key>match</key>
			<string>'.*'</string>
			<key>name</key>
			<string>string.quoted.single</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\#.*$</string>
			<key>name</key>
			<string>comment.line.dfl</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(&lt;|&gt;|=&lt;|&gt;=|=|:=|\+|-|\*)</string>
			<key>name</key>
			<string>keyword.operator.dfl</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(\sif\s|\sthen\s|\selse\s|\sfor\s|\sin\s)</string>
			<key>name</key>
			<string>keyword.control.dfl</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>^\s*(func)\s+(?=[A-Za-z_][A-Za-z0-9_]*\s*\()</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.type.function.dfl</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(\))</string>
			<key>name</key>
			<string>meta.function.dfl</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>(\D\S*)\s*(?=\()</string>
					<key>name</key>
					<string>entity.name.function.dfl</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>(\()</string>
					<key>end</key>
					<string>(?=\))</string>
					<key>name</key>
					<string>meta.function.parameters.dfl</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>match</key>
							<string>([^0-9,\)][^\),\r\n\t\f]*)</string>
							<key>name</key>
							<string>variable.parameter.dfl</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.dfl</string>
	<key>uuid</key>
	<string>534c4741-77e9-4267-bc3e-772d0aec3d83</string>
</dict>
</plist>
